interface Lead{
    id: string,
    contactId: number,
    agencyCode: string,
    dateRemote: string,
    fuel: string,
    mileageScalar: string,
    registerDate: string,
    advertiserName: string,
    advertiserPhone: string | null,
    price: number,
    url: string,
    userId: string,
    description: string,
    isConfirmed: boolean,
    manualSearch: number,
    isMessageSent: boolean,
    createdAt: string,
    oldNotes: string | null,
    rentStatus: string | null,
    advertiserCity: string,
    csvUrn: string,
    csvId: number,
    geoRegion: string,
    geoProvincia: string,
    geoTown: string,
    isSold: boolean,
    isVisible: boolean,
    spokiInterested: string | null,

    contactName: string,
    contactEmail: string | null,

    contactPhoneNumber: string | null,
    contactNotInterested: boolean,
    contactIsConfirmed: boolean,
    contactIsCommerciant: boolean,
    notesCount: number,
    
}